version: "3.8"
services:
   zk:
      image: confluentinc/cp-zookeeper:6.0.0
      network_mode: host
      user: root:appuser
      environment:
         - ZOOKEEPER_SERVER_ID=1
         - ZOOKEEPER_CLIENT_PORT=22181
         - ZOOKEEPER_TICK_TIME=2000
         - ZOOKEEPER_INIT_LIMIT=5
         - ZOOKEEPER_SYNC_LIMIT=2
         - ZOOKEEPER_ADMIN_SERVER_PORT=8028
         - ZOOKEEPER_SERVERS=127.0.0.1:22888:23888
#      entrypoint: bash -c "sh /etc/confluent/docker/run"
   kafka:
      image: confluentinc/cp-kafka:6.0.0
      network_mode: "host"
      environment:
         - KAFKA_ZOOKEEPER_CONNECT=127.0.0.1:22181
         - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:29092
         - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      entrypoint: bash -c "sleep 10 && /etc/confluent/docker/run"
   registry:
      image: confluentinc/cp-schema-registry:6.1.1
      network_mode: "host"
      environment:
         - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=127.0.0.1:22181
         - SCHEMA_REGISTRY_HOST_NAME=127.0.0.1
         - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8085
#      entrypoint: bash -c "sleep 10 && /etc/confluent/docker/run"   

